### PR TITLE
IDE-4895 update deploy 70 tests to solve the problem of missing dependencies

### PR DESCRIPTION
**Pull request by lily94299570**
update deploy 70 tests to solve the problem of missing dependencies

### CODE REVIEW

**Comment by lily94299570** [comment]
ft retest

**Comment by lily94299570** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
fr retest

**Comment by lily94299570** [comment]
ft retest

**Comment by lily94299570** [comment]
ft retest

**Comment by lily94299570** [comment]
ft retest

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Functional-Tests-Checker//1454

**Pull request closed without merging**
