### PR TITLE
IDE-4396 add watch workspace tests and sf

### PR DESCRIPTION
**Pull request by rui123wang**
Testing,don't merge,thanks

### CODE REVIEW

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//173

**Comment by rui123wang** [comment]
ft retest

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//174

**Comment by rui123wang** [comment]
ft retest

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//176

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//177

**Comment by rui123wang** [comment]
ft retest

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//178

**Comment by rui123wang** [comment]
ft retest

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//179

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//180

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//181

**Pull request closed without merging**
