### PR TITLE
Work-in-Progress testing mac build

### PR DESCRIPTION
**Pull request by gamerson**

### CODE REVIEW

**Comment by gamerson** [comment]
hey @yanan here is a commit where I tried to get the mac build working.  This was from my mac, but the idea should work in general for a linux install as well.  See if @jtydhr88 can help your get this working for both mac and windows and linux.  If we can't get this done by next wednesday we will just have to disable the mac build for M1 and try to get it working for M2.

**Comment by gamerson** [comment]
@yanan @jtydhr88 this now works for mac with the latest commit.  however for all other platforms it is broken.  So if you guys can take a look at the changes I made to support mac and then get it to work for all platforms that would be great, thanks!

**Comment by yanan** [comment]
New pr has been sent: https://github.com/gamerson/liferay-ide/pull/1348

**Comment by yanan** [comment]
Thanks so much for helping this.

**Pull request closed without merging**
