### PR TITLE
IDE-4926

### PR DESCRIPTION
**Pull request by simonjhy**

### CODE REVIEW

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Functional-Wizards-Tests//12

**Comment by yanan** [comment]
Integration Tests Build Failed.

Tests Failed on http://ide-build-1:9090/job/Integration-Tests-Checker//1391

**Comment by simonjhy** [comment]
CI:retest

**Comment by yanan** [comment]
Functional tests passed on CN Linux server on b1200beac0fcef1e626566bfe47755f622f8aaa0

http://ide-build-1:9090/job/Functional-Wizards-Tests//17

**Comment by yanan** [comment]
Integration Tests Build Failed.

Tests Failed on http://ide-build-1:9090/job/Integration-Tests-Checker//1398

**Pull request closed without merging**
