### PR TITLE
IDE-4396 add watch workspace tests and sf

### PR DESCRIPTION
**Pull request by rui123wang**
Testing,don't merge,thanks

### CODE REVIEW

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//182

**Comment by rui123wang** [comment]
ft retest

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//183

**Comment by rui123wang** [comment]
ft retest

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//184

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//185

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//186

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//187

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//188

**Comment by rui123wang** [comment]
ft retest

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//190

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//191

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//192

**Comment by yanan** [comment]
ft retest

**Comment by yanan** [comment]
Functional Tests build Failed.
Test Failed on http://ide-build-1:9090/job/Test-Checker//193

**Pull request closed without merging**
